name: Master_Flow

on: 
  workflow_dispatch:
    inputs:
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 
jobs:
  call-workflow-1:
    uses: ./.github/workflows/Flow1.yml
    with:
      TestEnv: ${{ github.event.inputs.TestEnv }}
    secrets: inherit
  call-workflow-2:
    uses: ./.github/workflows/Flow2.yml
    with:
      TestEnv: ${{ github.event.inputs.TestEnv }}
    secrets: inherit
  call-workflow-3:
    uses: ./.github/workflows/Flow3.yml
    with:
      TestEnv: ${{ github.event.inputs.TestEnv }}
    secrets: inherit
    

