name: TryEnvVariable

on: 
  workflow_dispatch:
    inputs:
      plan:
        type: choice
        description: Please select Test Plan For the execution
        options: 
        - Shop Floor
        - SOAPI
        - SYDATA-Sales_Order
        - System_Setup
        - Work Order
        - Temp
        - Test1
        - Test2
        - Test3

      
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 
  
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
       
      
    steps:
    - name: Get current date
      id: date
      run: |
        temp="${{github.event.inputs.plan}}" | echo "::set-output name=date::$(echo ${temp// /_})"

    - name: Set Plan Name
      id: PlanName
      run: temp="${{github.event.inputs.plan}}" | echo "::set-output name=TestName::$(echo ${temp// /_})"


    - name: Upload test file
      uses: actions/checkout@v1
    - run: echo "Execution Started for Test Plan ${{github.event.inputs.plan}} at ${{ steps.date.outputs.date }}"> ExecutionStarted.txt
    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: ExecutionStarted.txt
          channel: provar-gitaction
     
    - name: Execute Test Plan-${{github.event.inputs.plan}}
      run: |
        echo "Date-"${{ steps.date.outputs.date }}
        echo "TestPlan"${{ steps.PlanName.output.TestName}}